# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixInverse <- function(A) {
    .Call(`_CppMatrix_matrixInverse`, A)
}

matrixMultiply <- function(A, B) {
    .Call(`_CppMatrix_matrixMultiply`, A, B)
}

matrixVectorMultiply <- function(A, b) {
    .Call(`_CppMatrix_matrixVectorMultiply`, A, b)
}

matrixCor <- function(A) {
    .Call(`_CppMatrix_matrixCor`, A)
}

matrixEigen <- function(A) {
    .Call(`_CppMatrix_matrixEigen`, A)
}

matrixKronecker <- function(A, B) {
    .Call(`_CppMatrix_matrixKronecker`, A, B)
}

