# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixInverse_cpp <- function(A) {
    .Call(`_CppMatrix_matrixInverse_cpp`, A)
}

matrixMultiply_cpp <- function(A, B, transA = FALSE, transB = FALSE) {
    .Call(`_CppMatrix_matrixMultiply_cpp`, A, B, transA, transB)
}

matrixVectorMultiply_cpp <- function(A, b) {
    .Call(`_CppMatrix_matrixVectorMultiply_cpp`, A, b)
}

matrixCor_cpp <- function(A) {
    .Call(`_CppMatrix_matrixCor_cpp`, A)
}

matrixEigen_cpp <- function(A) {
    .Call(`_CppMatrix_matrixEigen_cpp`, A)
}

matrixKronecker_cpp <- function(A, B) {
    .Call(`_CppMatrix_matrixKronecker_cpp`, A, B)
}

matrixListProduct_cpp <- function(matrixList) {
    .Call(`_CppMatrix_matrixListProduct_cpp`, matrixList)
}

matrixGeneralizedInverse_cpp <- function(A, tol = 5e-16) {
    .Call(`_CppMatrix_matrixGeneralizedInverse_cpp`, A, tol)
}

matrixSylvesterEigen_cpp <- function(UA, DA, UB, DB, C) {
    .Call(`_CppMatrix_matrixSylvesterEigen_cpp`, UA, DA, UB, DB, C)
}

matrixSylvester_cpp <- function(A, B, C) {
    .Call(`_CppMatrix_matrixSylvester_cpp`, A, B, C)
}

matrixSVD_cpp <- function(A) {
    .Call(`_CppMatrix_matrixSVD_cpp`, A)
}

matrixSolveMat_cpp <- function(A, B) {
    .Call(`_CppMatrix_matrixSolveMat_cpp`, A, B)
}

matrixScale_cpp <- function(X, center = TRUE, standardized = TRUE, robust = FALSE) {
    .Call(`_CppMatrix_matrixScale_cpp`, X, center, standardized, robust)
}

